#ifndef _KERN_VIDEO_ERR_H
#define _KERN_VIDEO_ERR_H

#define E_VIDEO_SUCCESS 0
#define E_VIDEO_ARGNULL -1
#define E_VIDEO_INFO_TRUNCATED 1
#define E_VIDEO_UNSUPPORTED 2
#define E_VIDEO_ERROR 3


#endif